import { FormEvent, useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { AlertTriangle, Boxes, Camera, CheckCircle2, Package, Plus, ScanLine, Settings2, ShoppingCart, Warehouse } from 'lucide-react'
import type { IScannerControls } from '@zxing/browser'
import { supabase } from './lib/supabase'
import { writeError } from './lib/db'
import type { CommandeFournisseur, EmplacementStock, Fournisseur, HistoriqueInventaire, Materiel, Stock, StockEmplacement } from './types'
import { Empty, Modal, StockBadge } from './components'

const orderStatus={
  a_commander:{label:'À commander',className:'order-todo'},
  commande:{label:'Commandé',className:'order-ordered'},
  en_livraison:{label:'En livraison',className:'order-shipping'},
  recu:{label:'Reçu',className:'order-received'},
} as const

type EmailNotice={ok:boolean;text:string}

async function envoyerCommandeParEmail(commandeId:string){
 const {data:{session}}=await supabase.auth.getSession()
 if(!session)throw new Error('Votre session a expiré. Reconnectez-vous puis réessayez.')
 const response=await fetch('/api/envoyer-commande',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({commande_id:commandeId})})
 const payload=await response.json().catch(()=>({})) as {error?:string;destinataire?:string}
 if(!response.ok)throw new Error(payload.error||'Le service e-mail est indisponible.')
 return payload.destinataire||'le destinataire configuré'
}

export function OrdersView({groupId,stocks,orders,suppliers,locations,canEdit,showGroups,onReload,onEditThreshold}:{groupId:string;stocks:Stock[];orders:CommandeFournisseur[];suppliers:Fournisseur[];locations:EmplacementStock[];canEdit:boolean;showGroups:boolean;onReload:()=>void;onEditThreshold:(stock:Stock)=>void}){
 const [creating,setCreating]=useState(false),[busy,setBusy]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState<EmailNotice|null>(null)
 const suggestions=useMemo(()=>stocks.filter(s=>s.quantite<=s.seuil_alerte).map(s=>({...s,quantite_a_commander:Math.max(0,s.stock_cible-s.quantite)})).filter(s=>s.quantite_a_commander>0),[stocks])
 const depot=locations.find(l=>l.type==='depot'&&l.disponible)
 async function changeStatus(order:CommandeFournisseur,statut:CommandeFournisseur['statut']){setBusy(order.id);setError('');const e=writeError(await supabase.from('commandes_fournisseurs').update({statut,date_commande:statut==='commande'?(order.date_commande||new Date().toISOString().slice(0,10)):order.date_commande,updated_at:new Date().toISOString()}).eq('id',order.id).select('id'),'Aucune ligne modifiée : vos droits ne couvrent pas ce groupe, ou la fiche a été modifiée entre-temps.');setBusy('');if(e)setError(e.message);else onReload()}
 async function receive(order:CommandeFournisseur){if(!depot){setError('Le dépôt de réception est introuvable.');return}setBusy(order.id);setError('');const {error:e}=await supabase.rpc('receptionner_commande',{p_commande_id:order.id,p_emplacement_id:depot.id});setBusy('');if(e)setError(e.message);else onReload()}
 return <div className="feature-stack">
  <section className="panel full">
   <div className="toolbar"><div><h3>Alertes et liste de commande</h3><p>Les quantités proposées complètent le stock jusqu’au niveau cible.</p></div>{canEdit&&<button className="primary" disabled={!suggestions.length} onClick={()=>{setNotice(null);setCreating(true)}}><ShoppingCart/>Créer une commande</button>}</div>
   <div className="alert-order-list">{suggestions.map(s=><div key={s.id} className="alert-order-row"><div className="item-icon"><Package/></div><div className="alert-order-name"><strong>{s.materiels.nom}</strong><span>{s.materiels.code} · seuil {s.seuil_alerte} · cible {s.stock_cible}</span></div><div className="alert-order-qty"><span>En stock</span><b>{s.quantite}</b></div><div className="alert-order-qty suggested"><span>À commander</span><b>{s.quantite_a_commander}</b></div><StockBadge q={s.quantite} seuil={s.seuil_alerte}/>{canEdit&&<button className="edit-move" onClick={()=>onEditThreshold(s)} title="Modifier le seuil et la cible"><Settings2/><span>Régler</span></button>}</div>)}{!suggestions.length&&<Empty title="Aucune commande nécessaire" text="Tous les articles sont au-dessus de leur seuil."/>}</div>
  </section>
  <section className="panel full orders-panel">
   <div className="toolbar"><div><h3>Commandes fournisseurs</h3><p>Suivi depuis la préparation jusqu’à la réception au dépôt.</p></div><span>{orders.length} commande{orders.length>1?'s':''}</span></div>
   {error&&<div className="form-error">{error}</div>}{notice&&<div className={notice.ok?'notice':'form-error'}>{notice.text}</div>}
   <div className="orders-grid">{orders.map(order=>{const status=orderStatus[order.statut];return <article className="order-card" key={order.id}><header><div><span className="eyebrow">{showGroups&&`${order.groupe_id} · `}{order.reference}</span><h3>{order.fournisseurs?.nom||'Fournisseur non renseigné'}</h3></div><span className={`order-status ${status.className}`}>{status.label}</span></header><div className="order-lines">{order.lignes_commande.map(line=><div key={line.id}><span>{line.materiels.nom}</span><b>{line.quantite_recue}/{line.quantite_commandee} {line.materiels.unite}</b></div>)}</div>{order.commentaire&&<p>{order.commentaire}</p>}<footer>{canEdit&&order.statut!=='recu'?<><label>Statut<select value={order.statut} disabled={busy===order.id} onChange={e=>changeStatus(order,e.target.value as CommandeFournisseur['statut'])}><option value="a_commander">À commander</option><option value="commande">Commandé</option><option value="en_livraison">En livraison</option></select></label>{['commande','en_livraison'].includes(order.statut)&&<button className="primary" disabled={busy===order.id} onClick={()=>receive(order)}><CheckCircle2/>{busy===order.id?'Réception…':'Réceptionner'}</button>}</>:<span>{order.statut==='recu'?'Stock mis à jour automatiquement':'Lecture seule'}</span>}</footer></article>})}</div>
   {!orders.length&&<Empty icon="alert" title="Aucune commande fournisseur" text="Créez une commande à partir de la liste d’alertes."/>}
  </section>
  {creating&&<CreateOrderForm groupId={groupId} suggestions={suggestions} suppliers={suppliers} onClose={()=>setCreating(false)} onDone={result=>{setCreating(false);setNotice(result);onReload()}}/>}
 </div>
}

function CreateOrderForm({groupId,suggestions,suppliers,onClose,onDone}:{groupId:string;suggestions:Array<Stock&{quantite_a_commander:number}>;suppliers:Fournisseur[];onClose:()=>void;onDone:(result:EmailNotice)=>void}){
 const [selected,setSelected]=useState<Record<string,boolean>>({}),[quantities,setQuantities]=useState<Record<string,number>>(()=>Object.fromEntries(suggestions.map(s=>[s.materiel_id,s.quantite_a_commander]))),[supplier,setSupplier]=useState(''),[comment,setComment]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 const submittingRef=useRef(false)
 const selectedCount=Object.values(selected).filter(Boolean).length
 async function submit(event:FormEvent){event.preventDefault();if(submittingRef.current)return;const lines=suggestions.filter(s=>selected[s.materiel_id]).map(s=>({materiel_id:s.materiel_id,quantite:quantities[s.materiel_id]}));if(!lines.length){setError('Sélectionnez au moins un article.');return}submittingRef.current=true;setBusy(true);setError('');const {data:commandeId,error:dbError}=await supabase.rpc('creer_commande',{p_fournisseur_nom:supplier,p_lignes:lines,p_commentaire:comment||null,p_groupe_id:groupId});if(dbError||!commandeId){submittingRef.current=false;setBusy(false);setError(dbError?.message||'La commande n’a pas pu être créée.');return}try{const destinataire=await envoyerCommandeParEmail(String(commandeId));setBusy(false);onDone({ok:true,text:`Commande créée et envoyée à ${destinataire}.`})}catch(emailError){setBusy(false);onDone({ok:false,text:`Commande créée, mais e-mail non envoyé : ${emailError instanceof Error?emailError.message:'erreur inconnue'}`})}}
 return <Modal title="Nouvelle commande fournisseur" onClose={onClose}><form className="form order-form" onSubmit={submit}><label>Fournisseur<input list="supplier-list" value={supplier} onChange={e=>setSupplier(e.target.value)} placeholder="Nom du fournisseur"/><datalist id="supplier-list">{suppliers.map(s=><option value={s.nom} key={s.id}/>)}</datalist></label><div className="order-selection"><div className="selection-title"><strong>Articles à commander</strong><span>{selectedCount} sélectionné{selectedCount>1?'s':''}</span></div>{suggestions.map(s=><div className="order-choice" key={s.id}><input aria-label={`Sélectionner ${s.materiels.nom}`} type="checkbox" checked={!!selected[s.materiel_id]} onChange={e=>setSelected(v=>({...v,[s.materiel_id]:e.target.checked}))}/><span><b>{s.materiels.nom}</b><small>Stock {s.quantite} · cible {s.stock_cible}</small></span><input aria-label={`Quantité de ${s.materiels.nom}`} type="number" min="1" value={quantities[s.materiel_id]} onChange={e=>setQuantities(v=>({...v,[s.materiel_id]:Number(e.target.value)}))}/></div>)}</div><label>Commentaire<textarea rows={2} value={comment} onChange={e=>setComment(e.target.value)} placeholder="Référence, délai ou information utile…"/></label>{error&&<div className="form-error">{error}</div>}<button className="primary wide" disabled={busy||!selectedCount}>{busy?'Création et envoi…':'Créer et envoyer la commande'}</button></form></Modal>
}

export function ThresholdForm({stock,onClose,onDone}:{stock:Stock;onClose:()=>void;onDone:()=>void}){
 const [threshold,setThreshold]=useState(stock.seuil_alerte),[target,setTarget]=useState(stock.stock_cible),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 async function submit(event:FormEvent){event.preventDefault();if(target<threshold){setError('Le stock cible doit être supérieur ou égal au seuil.');return}setBusy(true);const dbError=writeError(await supabase.from('stocks').update({seuil_alerte:threshold,stock_cible:target}).eq('id',stock.id).select('id'),'Aucune ligne modifiée : vos droits ne couvrent pas ce groupe, ou la fiche a été modifiée entre-temps.');setBusy(false);if(dbError)setError(dbError.message);else onDone()}
 return <Modal title={`Régler · ${stock.materiels.nom}`} onClose={onClose}><form className="form" onSubmit={submit}><p>Le seuil déclenche l’alerte. La cible sert à calculer la quantité à commander.</p><div className="field-row"><label>Seuil d’alerte<input type="number" min="0" required value={threshold} onChange={e=>setThreshold(Number(e.target.value))}/></label><label>Stock cible<input type="number" min="0" required value={target} onChange={e=>setTarget(Number(e.target.value))}/></label></div>{error&&<div className="form-error">{error}</div>}<button className="primary wide" disabled={busy}>{busy?'Enregistrement…':'Enregistrer les niveaux'}</button></form></Modal>
}

export function InventoryAdjustmentForm({stock,locations,locationStocks,onClose,onDone}:{stock:Stock;locations:EmplacementStock[];locationStocks:StockEmplacement[];onClose:()=>void;onDone:()=>void}){
 const available=locations.filter(location=>location.actif&&location.disponible)
 const defaultLocation=available.find(location=>location.type==='depot')?.id||available[0]?.id||''
 const quantityAt=(locationId:string)=>locationStocks.find(row=>row.materiel_id===stock.materiel_id&&row.emplacement_id===locationId)?.quantite||0
 const [locationId,setLocationId]=useState(defaultLocation),[counted,setCounted]=useState(()=>quantityAt(defaultLocation)),[comment,setComment]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 const current=quantityAt(locationId),difference=counted-current,selectedLocation=available.find(location=>location.id===locationId)
 function changeLocation(nextLocationId:string){setLocationId(nextLocationId);setCounted(quantityAt(nextLocationId))}
 async function submit(event:FormEvent){event.preventDefault();if(!locationId){setError('Aucun emplacement disponible.');return}if(!Number.isInteger(counted)||counted<0){setError('La quantité comptée doit être un nombre entier positif ou zéro.');return}setBusy(true);setError('');const {error:dbError}=await supabase.rpc('ajuster_inventaire_stock',{p_materiel_id:stock.materiel_id,p_emplacement_id:locationId,p_quantite_comptee:counted,p_commentaire:comment.trim()||null});setBusy(false);if(dbError)setError(dbError.message);else onDone()}
 return <Modal title={`Inventaire · ${stock.materiels.nom}`} onClose={onClose}><form className="form inventory-form" onSubmit={submit}><div className="notice"><CheckCircle2/>Cet ajustement remplace la quantité de l’emplacement. Il ne crée aucun mouvement de stock.</div><label>Emplacement<select value={locationId} onChange={event=>changeLocation(event.target.value)} required>{available.map(location=><option value={location.id} key={location.id}>{location.nom}</option>)}</select></label><div className="inventory-counts"><div><span>Quantité enregistrée</span><strong>{current}</strong><small>{stock.materiels.unite}</small></div><label>Quantité réellement comptée<input type="number" min="0" step="1" required value={counted} onChange={event=>setCounted(Number(event.target.value))}/></label></div><div className={`inventory-difference ${difference===0?'neutral':difference>0?'positive':'negative'}`}><span>Écart à appliquer</span><strong>{difference>0?'+':''}{difference} {stock.materiels.unite}</strong></div><label>Commentaire facultatif<textarea rows={2} value={comment} onChange={event=>setComment(event.target.value)} placeholder="Ex. inventaire mensuel, correction de comptage…"/></label><p className="form-hint">Le stock global sera recalculé automatiquement après validation pour {selectedLocation?.nom||'cet emplacement'}.</p>{error&&<div className="form-error">{error}</div>}<button className="primary wide" disabled={busy||!locationId}>{busy?'Ajustement…':'Valider l’inventaire'}</button></form></Modal>
}

const locationTabs=[['all','Tous'],['depot','Dépôt'],['hs','Hors service'],['perdu','Perdu']] as const
const locationIcons={depot:Warehouse,hs:AlertTriangle,perdu:Boxes} as const

export function LocationsView({locations,locationStocks,showGroups}:{locations:EmplacementStock[];locationStocks:StockEmplacement[];showGroups:boolean}){
 const [filter,setFilter]=useState<(typeof locationTabs)[number][0]>('depot')
 const visible=filter==='all'?locations:locations.filter(l=>l.type===filter)
 return <section className="panel full"><div className="toolbar"><div><h3>Stock par emplacement</h3><p>Dépôt et matériel indisponible (hors service, perdu).</p></div><span>{locations.length} emplacements</span></div><div className="location-tabs">{locationTabs.map(([id,label])=><button key={id} className={filter===id?'active':''} onClick={()=>setFilter(id)}>{label}</button>)}</div><div className="location-grid">{visible.map(location=>{const Icon=locationIcons[location.type],items=locationStocks.filter(s=>s.emplacement_id===location.id&&s.quantite>0),total=items.reduce((sum,item)=>sum+item.quantite,0);return <article className={`location-card ${location.disponible?'':'unavailable'}`} key={location.id}><header><div className="location-icon"><Icon/></div><div><span>{showGroups&&`${location.groupe_id} · `}{location.type}</span><h3>{location.nom}</h3></div><b>{total}</b></header><div className="location-items">{items.map(item=><div key={item.id}><span>{item.materiels.nom}</span><b>{item.quantite} {item.materiels.unite}</b></div>)}{!items.length&&<span className="location-empty">Aucun article dans cet emplacement</span>}</div></article>})}</div>{!visible.length&&<Empty title="Aucun emplacement" text="Aucun emplacement ne correspond à ce filtre."/>}</section>
}

const historyDate=new Intl.DateTimeFormat('fr-FR',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'})

export function HistoriqueView({rows,showGroups}:{rows:HistoriqueInventaire[];showGroups:boolean}){
 return <section className="panel full equipment-panel">
  <div className="equipment-panel-head"><div><h3>Historique des comptages</h3><p>Ajustements d’inventaire, du plus récent au plus ancien.</p></div><span>{rows.length} entrée{rows.length>1?'s':''}</span></div>
  <div className="equipment-table-wrap"><table className="equipment-table"><thead><tr><th>Date</th>{showGroups&&<th>Groupe</th>}<th>Article</th><th>Emplacement</th><th>Avant → Compté</th><th>Écart</th><th>Saisi par</th><th>Commentaire</th></tr></thead><tbody>
   {rows.map(row=>{const diff=row.quantite_comptee-row.quantite_avant;return <tr key={row.id}><td>{historyDate.format(new Date(row.created_at))}</td>{showGroups&&<td><span className="group-chip">{row.groupe_id}</span></td>}<td><b>{row.materiel_nom}</b><br/><small>{row.materiel_code}</small></td><td>{row.emplacement_nom}</td><td>{row.quantite_avant} → {row.quantite_comptee}</td><td className={`history-diff ${diff>0?'positive':diff<0?'negative':''}`}>{diff>0?'+':''}{diff}</td><td>{row.saisi_par_nom}</td><td>{row.commentaire||'—'}</td></tr>})}
  </tbody></table></div>
  {!rows.length&&<Empty title="Aucun comptage enregistré" text="Les ajustements d’inventaire depuis l’onglet Stocks apparaîtront ici."/>}
 </section>
}

export function ScannerModal({stocks,canEdit,onClose,onPick,onReload}:{stocks:Stock[];canEdit:boolean;onClose:()=>void;onPick:(materialId:string,type:string)=>void;onReload:()=>void}){
 const videoRef=useRef<HTMLVideoElement|null>(null),controlsRef=useRef<IScannerControls|null>(null)
 const [cameraOn,setCameraOn]=useState(false),[code,setCode]=useState(''),[found,setFound]=useState<Materiel|null>(null),[unknown,setUnknown]=useState(false),[associate,setAssociate]=useState(stocks[0]?.materiel_id||''),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 const materials=useMemo(()=>stocks.map(s=>s.materiels),[stocks])
 const processCode=useCallback((raw:string)=>{const value=raw.trim();setCode(value);const match=materials.find(m=>m.code.toLowerCase()===value.toLowerCase()||m.code_barres?.toLowerCase()===value.toLowerCase())||null;setFound(match);setUnknown(!match);setError('');if(match){controlsRef.current?.stop();setCameraOn(false)}},[materials])
 useEffect(()=>{if(!cameraOn||!videoRef.current)return;let cancelled=false;setError('');import('@zxing/browser').then(async({BrowserMultiFormatReader})=>{const reader=new BrowserMultiFormatReader();const controls=await reader.decodeFromConstraints({video:{facingMode:{ideal:'environment'}}},videoRef.current||undefined,(result,_error,currentControls)=>{controlsRef.current=currentControls;if(result&&!cancelled)processCode(result.getText())});if(cancelled)controls.stop();else controlsRef.current=controls}).catch(()=>{if(!cancelled){setError('Impossible d’ouvrir la caméra. Vous pouvez saisir le code manuellement.');setCameraOn(false)}});return()=>{cancelled=true;controlsRef.current?.stop();controlsRef.current=null}},[cameraOn,processCode])
 function manualSubmit(e:FormEvent){e.preventDefault();if(code.trim())processCode(code)}
 async function linkCode(){if(!associate||!code.trim())return;setBusy(true);setError('');const e=writeError(await supabase.from('materiels').update({code_barres:code.trim()}).eq('id',associate).select('id'),'Aucune ligne modifiée : vos droits ne couvrent pas ce groupe, ou la fiche a été modifiée entre-temps.');setBusy(false);if(e)setError(e.message);else{const material=materials.find(m=>m.id===associate)||null;setFound(material?{...material,code_barres:code.trim()}:null);setUnknown(false);onReload()}}
 return <Modal title="Scanner un article" onClose={onClose}><div className="scanner"><div className={`camera-frame ${cameraOn?'active':''}`}>{cameraOn?<video ref={videoRef} autoPlay muted playsInline/>:<div><ScanLine/><strong>Scan QR ou code-barres</strong><span>Utilisez la caméra arrière du téléphone.</span></div>}</div>{!cameraOn&&<button className="primary wide" onClick={()=>setCameraOn(true)}><Camera/>Activer la caméra</button>}<form className="manual-scan" onSubmit={manualSubmit}><label>Ou saisir le code manuellement<input value={code} onChange={e=>setCode(e.target.value)} placeholder="Ex. gants_8 ou code-barres"/></label><button className="edit-move">Rechercher</button></form>{error&&<div className="form-error">{error}</div>}{found&&<div className="scan-result"><div className="item-icon"><Package/></div><div><span>Article reconnu</span><strong>{found.nom}</strong><small>{found.code}</small></div><div className="scan-actions"><button onClick={()=>onPick(found.id,'entree')}>Entrée</button><button onClick={()=>onPick(found.id,'sortie')}>Sortie</button><button onClick={()=>onPick(found.id,'transfert')}>Transfert</button>{canEdit&&<button onClick={()=>onPick(found.id,'inventaire')}>Inventaire</button>}</div></div>}{unknown&&<div className="scan-unknown"><AlertTriangle/><div><strong>Code non associé</strong><span>{canEdit?'Associez-le une fois à un article.':'Demandez à un responsable d’associer ce code.'}</span></div>{canEdit&&<><select value={associate} onChange={e=>setAssociate(e.target.value)}>{stocks.map(s=><option value={s.materiel_id} key={s.id}>{s.materiels.nom}</option>)}</select><button className="primary" disabled={busy} onClick={linkCode}><Plus/>{busy?'Association…':'Associer'}</button></>}</div>}</div></Modal>
}
